---
- hosts: all

  sudo: True

  vars_files:
    - vars/apt.yml
    - vars/users.yml
    - vars/nginx.yml
    - vars/nodejs.yml
    - vars/postgresql.yml

  roles:
    - role: kosssi.apt
      tag: apt

    - role: ANXS.generic-users
      tag: users

    - role: jdauphant.nginx
      tag: nginx

    - role: ANXS.nodejs
      tag: nodejs

    - role: ANXS.postgresql
      tag: postgresql

  tasks:
    - name: set locale LC_ALL
      lineinfile: dest=/etc/default/locale line="LC_ALL=en_US.UTF-8"

    - name: set locale LANGUAGE
      lineinfile: dest=/etc/default/locale line="LANGUAGE=en_US:en"
